### ISSUE TITLE
KiCAD schematic does not have the cache file

### ISSUE THREAD

**Issue by blu006** [softegg/Stylish-Trucker-Belt-Synthesizer#1]
This issue is raised with https://github.com/softegg/Stylish-Trucker-Belt-Synthesizer/blob/0fc1f83537cc46e5045114e1b37d2316abffe41a/MAG%20Synth/Stylish-Belt-Synth%20-%20Full.sch 

On trying to open the kicad schematic file, the following message shows up.

![image](https://github.com/softegg/Stylish-Trucker-Belt-Synthesizer/assets/1582189/2ca2913e-5183-40c9-b519-cde264edfe40)

With the schematic file open, many symbols are missing.
![Stylish-Belt-Synth - Full](https://github.com/softegg/Stylish-Trucker-Belt-Synthesizer/assets/1582189/2aeebc87-b391-49c0-9ff8-d751b2628b15)

![Stylish-Belt-Synth - Full-WS2812B-16-LED-RING](https://github.com/softegg/Stylish-Trucker-Belt-Synthesizer/assets/1582189/19b325c4-f9fd-4092-9ef8-545a04cb6a58)

It is recommended that the ...cache.lib file is uploaded.

**Comment by softegg** [comment]
Oopsie!
I added the cache.lib file that it asked for.
It's so hard to tell which files are necessary and which are cruft... 
Please let me know if there are any further difficulties!

**Comment by blu006** [comment]
Were the project files for `Stylish-Belt-Synth - Full` renamed? 

The file in commit ebaa3cd6d5b41de6f620a7fdb4b774d3655a4098 is named `Stylish-Belt-Synth-cache.lib`, not the necessary `Stylish-Belt-Synth -Full-cache.lib`.

**Comment by softegg** [comment]
Oh, it wanted that one.
It's in now.
I think I copied it by exporting the project, but I really don't remember.
It became "full" for disambiguation when I started making split versions so that it could be cut in two parts on my PCB mill for prototyping.
Git confuses me.

**Comment by blu006** [comment]
you can write that in a readme file in the `MAG Synth` folder.
