### ISSUE TITLE
Out of tune

### ISSUE THREAD

**Issue by MichaelJuan** [softegg/Stylish-Trucker-Belt-Synthesizer#3]
Default scale  when powered on is offset by 4 scale steps. one of the notes is just wrong even with the offset. It should be F but its F#.

**Comment by softegg** [comment]
I believe I fixed the offset issue on release at MAGwest.
Have you tried it with the latest firmware?

**Comment by MichaelJuan** [comment]
Ok will updtae maglab synth later.
